import { db, publicLaunch } from "../../../lib/db.js";
import { currentUser } from "../../../lib/server-auth.js";
import { checklistAccess } from "../../../lib/product-access.js";
import { launchHandlers } from "../../../lib/launch-handlers.js";
import { limitByIp } from "../../../lib/rate-limit.js";
export const dynamic = "force-dynamic";
const handlers = launchHandlers({ user: currentUser, db, serialize: publicLaunch, entitled: checklistAccess, limit: limitByIp });
export const GET = handlers.GET;
export const POST = handlers.POST;
export const PATCH = handlers.PATCH;
