export const LAUNCH_STEPS = [
  {
    id: "name",
    label: "Name locked",
    hint: "One company. Do not launch ten in one shot.",
  },
  {
    id: "one_liner",
    label: "One-sentence product",
    hint: "What it does, in one line.",
  },
  {
    id: "domain",
    label: "Domain decided",
    hint: "DNS is an Awad click. Ship on vercel.app until then.",
  },
  {
    id: "repo",
    label: "GitHub repo exists",
    hint: "313aidaroos/<name>. Clone to ~/src/<name>.",
  },
  {
    id: "vercel",
    label: "Vercel project live",
    hint: "Deploy to this company's project. No tokens in chat.",
  },
  {
    id: "waitlist",
    label: "Waitlist before payments",
    hint: "Collect emails. Do not flip Stripe live.",
  },
  {
    id: "chrome",
    label: "Family chrome on the site",
    hint: "A Apixis Company.",
  },
  {
    id: "stripe_test",
    label: "Stripe test mode only",
    hint: "Live charges need Awad. Test mode is fine.",
  },
  {
    id: "usable_site",
    label: "Live site is usable",
    hint: "Not a mock. Not a coming-soon page.",
  },
  {
    id: "env_isolated",
    label: "Env is this company only",
    hint: "Do not mix another company's env into this launch.",
  },
];

export function emptyItems() {
  return LAUNCH_STEPS.map((s) => ({ id: s.id, done: false }));
}

export function mergeItems(existing) {
  const byId = new Map((existing || []).map((i) => [i.id, i]));
  return LAUNCH_STEPS.map((s) => ({
    id: s.id,
    done: Boolean(byId.get(s.id)?.done),
  }));
}

export const FAMILY_SEED = [
  {
    slug: "launchixis",
    name: "Launchixis",
    one_liner: "Launch operations for new Apixis-family companies.",
    domain: "",
    repo: "313aidaroos/Launchixis",
    vercel_project: "launchixis",
    status: "active",
    notes: "Ops board. One sister company at a time.",
    items: [
      { id: "name", done: true },
      { id: "one_liner", done: true },
      { id: "domain", done: false },
      { id: "repo", done: true },
      { id: "vercel", done: false },
      { id: "waitlist", done: false },
      { id: "chrome", done: false },
      { id: "stripe_test", done: false },
      { id: "usable_site", done: false },
      { id: "env_isolated", done: true },
    ],
  },
  {
    slug: "apixis",
    name: "Apixis",
    one_liner: "Virtual world and economy for AI agents.",
    domain: "apixis.dev",
    repo: "313aidaroos/Apixis.dev",
    vercel_project: "apixis-dev-1iqh",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "socixis",
    name: "Socixis",
    one_liner: "AI marketing and social. Cixy lives here only.",
    domain: "socixis.dev",
    repo: "313aidaroos/Socixis",
    vercel_project: "socixis",
    status: "not_started",
    notes: "Cixy stays in Socixis. Do not rebuild her as a cross-company OS.",
    items: emptyItems(),
  },
  {
    slug: "awadbot",
    name: "AwadBot",
    one_liner: "Personal financier for Awad.",
    domain: "",
    repo: "313aidaroos/AwadBot",
    vercel_project: "awadbot",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "awad-command",
    name: "Awad Command",
    one_liner: "Private 3D dashboard / AI command center.",
    domain: "",
    repo: "313aidaroos/awad-command",
    vercel_project: "awad-command",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "contentbot",
    name: "PersonalContentBot",
    one_liner: "One-minute social videos.",
    domain: "",
    repo: "313aidaroos/PersonalContentBot",
    vercel_project: "",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "contraxis",
    name: "Contraxis",
    one_liner: "Homeowners and contractors matched with AI.",
    domain: "",
    repo: "313aidaroos/Contraxis.dev",
    vercel_project: "contraxis-dev",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "geoxis",
    name: "Geoxis",
    one_liner: "Live 3D map of company movement in the real world.",
    domain: "",
    repo: "313aidaroos/Geoxis",
    vercel_project: "",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "halaxis",
    name: "Halaxis",
    one_liner: "Halal and Sharia-compliant hedge fund.",
    domain: "",
    repo: "313aidaroos/Halaxis.dev",
    vercel_project: "halaxis",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "lyrixis",
    name: "Lyrixis",
    one_liner: "Music metadata, lyrics, catalog intelligence.",
    domain: "",
    repo: "313aidaroos/Lyrixis",
    vercel_project: "lyrixis",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "qahwahworld",
    name: "Qahwahworld",
    one_liner: "Specialty coffee marketplace.",
    domain: "",
    repo: "313aidaroos/qahwahworld",
    vercel_project: "qahwahworld",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "rawixis",
    name: "Rawixis",
    one_liner: "B2B market for critical raw materials, import/export, logistics.",
    domain: "",
    repo: "313aidaroos/Rawixis.dev",
    vercel_project: "rawixis",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
  {
    slug: "recovra",
    name: "Recovra",
    one_liner: "Overcharge recovery for companies.",
    domain: "",
    repo: "313aidaroos/Recovra",
    vercel_project: "recovra",
    status: "not_started",
    notes: "",
    items: emptyItems(),
  },
];
